<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $versionManager \Magento\Search\ViewModel\AdditionalSearchFormData */
$additionalSearchFormData = $block->getData('additionalSearchFormData');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
?>
<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $versionManager \Magento\Search\ViewModel\AdditionalSearchFormData */
$additionalSearchFormData = $block->getData('additionalSearchFormData');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
?>
<!-- Modal -->
<div id="search-modal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <span class="close">&times;</span>
        </div>
        <div class="modal-body">
            <form class="form minisearch" id="search_mini_form" action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
                <?php if (!empty($queryParams = $additionalSearchFormData->getFormData())) : ?>
                    <?php foreach ($queryParams as $param) : ?>
                        <input type="hidden" name="<?= $escaper->escapeHtmlAttr($param['name']) ?>" value="<?= $escaper->escapeHtmlAttr($param['value']) ?>" />
                    <?php endforeach; ?>
                <?php endif; ?>
                <div class="field search">
                    <div class="control">
                        <input id="search" data-mage-init='{
                                "quickSearch": {
                                    "formSelector": "#search_mini_form",
                                    "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                    "destinationSelector": "#search_autocomplete",
                                    "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                                }
                            }' type="text" name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>" value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>" placeholder="<?= $escaper->escapeHtmlAttr(__('Type here to search')) ?>" class="input-text" maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" aria-expanded="false" />
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?= $block->getChildHtml() ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
    ], function($) {
        const searchIcon = $('.bi-search');
        const modal = $('#search-modal');
        const closeBtn = $('.close');
        searchIcon.on('click', () => {
            modal.addClass('show');
        });
        closeBtn.on('click', () => {
            modal.removeClass('show');
        });
    });
</script>