<div class="owl-carousel banner-list">
  <div class="item">
      <img src="https://www.thebodyshop.com.sa/east/pub/media/absolute_advancedslider/image/2023-Q1-RAMADAN-GET-READY-GIFT-LFS-CT1-200pc-DT_1.jpg" alt="">
      <div class="caption">
        <strong>LIFT THEIR SPIRITS</strong>
        <p>Celebrate as one with NEW, limited edition, Eid gifts that<br>
          bring joy to more than one.
        </p>
        <div class="button-caption">
          <button>Shop Gifts Now</button>
        </div>
      </div>
  </div>
</div>
