<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <button id="qty-decrease" class="decrease" onclick="decreaseQuantity(event)">-</button>
                <input type="number"
                       name="qty"
                       id="quantityRaw"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button id="qty-increase" class="increase" onclick="increaseQuantity(event)">+</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/javascript">
    function increaseQuantity(event) {
        event.preventDefault();
        var qty = parseInt(jQuery('#quantityRaw').val());
        jQuery('#quantityRaw').val(qty + 1);
        // jQuery('#product-addtocart-button').prop('disabled', true);
    }
    function decreaseQuantity(event) {
        event.preventDefault();
        var qty = parseInt(jQuery('#quantityRaw').val());
        if (qty > 1) {
            jQuery('#quantityRaw').val(qty - 1);
        }
        // jQuery('#product-addtocart-button').prop('disabled', true);
    }
</script>
