<div class="menu">
    <div class="menu__column">
        <h4><?php echo __('HERE TO HELP')?></h4>
        <ul>
            <li><a href="#" class="sub-text-footer"><?php echo __('You can contact us via Email')?></a></li>
            <li><a href="#" class="sub-text-footer"><?php echo __('support@thebodyshopeast.com')?></a></li>
            <li><a href="#" class="sub-text-footer"><?php echo __('Live chat')?></a></li>
            <li><a href="#" class="sub-text-footer"><?php echo __('SUN TO THU : 9AM TO 5PM')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('USERFUL INFORMATION')?></h4>
        <ul>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Delivery information and Return')?>"><?php echo __('Delivery information and Return')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Policy')?>"><?php echo __('Policy')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Term and conditions')?>"><?php echo __('Term and conditions')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Private Notice')?>"><?php echo __('Private Notice')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('SITE')?></h4>
        <ul>
        <li><a href="#" class="sub-text-footer" title="<?php echo __('Sitemap')?>"><?php echo __('Sitemap')?></a></li>
        </ul>
    </div>
    <div class="menu__column">
        <h4><?php echo __('ABOUT US')?></h4>
        <ul>
        <li><a href="#" class="sub-text-footer" title="<?php echo __('Who we are')?>"><?php echo __('Who we are')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Plastics')?>"><?php echo __('Plastics')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Again animals Testing')?>"><?php echo __('Again animals Testing')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Natura & Co')?>"><?php echo __('Natura & Co')?></a></li>
            <li><a href="#" class="sub-text-footer" title="<?php echo __('Ingredient Hub')?>"><?php echo __('Ingredient Hub')?></a></li>
        </ul>
    </div>
</div>