<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<div class="col-lg-4">
    <ul class="header-content-left-list">
        <li class="header-content-li" style="margin-right: 15px;margin-top: 5px;">
            <?php if (count($block->getStores()) > 1) : ?>
                <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
                <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
                    <!-- <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong> -->
                    <div class="actions dropdown menu options switcher-options">
                        <div class="action toggle switcher-trigger menu-title" id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" data-trigger-keypress-button="true">
                            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                                <span style="color:#f8f3e8;"><?= $block->escapeHtml($block->getStoreName()) ?></span>
                            </strong>
                        </div>
                        <ul class="dropdown switcher-dropdown menu-dropdown" data-target="dropdown">
                            <?php foreach ($block->getStores() as $_lang) : ?>
                                <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                                        <a style="text-decoration: none;color:#004236;font-size:15px;" href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                            <?= $block->escapeHtml($_lang->getName()) ?>
                                        </a>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        </li>
        <li class="header-content-li" style="margin-top: 2px;color: #111;font-weight: 600;text-decoration:none!important;">
            <a style="color: #f8f3e8;
    font-size: 15px;
    line-height: 24px;
    font-weight: 500;
    text-decoration: none;" href="https://www.thebodyshop.com.sa/east/en/store-locator/">SHOPS <i class="bi bi-geo-alt"></i></a>
        </li>
    </ul>
</div>