<div class="head-head" style=" background-color: #fff;
    background-image: linear-gradient(to bottom, #3d5d8e, #ffffff);
    width: 100%;
    display: flex;
    position: relative;
    justify-content: center;
    flex-direction: column;
    align-items: center;
    border: 1px solid #ccc;
    border-radius: 25px;">
    <div class="cover-image">
        <img style="width:100%;
        position:relative;
    height: 600px;
    overflow: hidden;
    border-radius: 25px;" src="https://scontent.fdad1-3.fna.fbcdn.net/v/t39.30808-6/321427625_816257342805327_7042373624703347977_n.png?_nc_cat=104&ccb=1-7&_nc_sid=e3f864&_nc_ohc=J4cvEksEwpEAX--BDyf&_nc_oc=AQlg82SQO6AWiRNJsW7QuSj0KUHyodgicAQ7HstaPTOSPENeerNdC0sqU8GxRBa24k4&_nc_ht=scontent.fdad1-3.fna&oh=00_AfB3KcsA92Buw7LTNK7B4U_c7BLQcHzWI8mHREeYYADRRQ&oe=641DDDC1" alt="" class="cover-photo" style="width: 100%;">
        <div class="profile-main" style="position: absolute;
        width:100%;">
            <img style="width: 250px;
                border: 7px solid white;
    aspect-ratio: 1/1;
    border-radius: 50%;
    overflow: hidden;
    position: absolute;
    top: 0;
    left: 0;
    margin-top: -50px;
    margin-left: 3%;" src="https://scontent.fdad1-3.fna.fbcdn.net/v/t39.30808-6/297339885_1107390716582779_822634812724291742_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=7FSBQKXNQuoAX-Rvtm7&_nc_ht=scontent.fdad1-3.fna&oh=00_AfAJfHL3d6kR_RQiHMCAXnEegvzvmK4htaEhslEmYymVeg&oe=641E2BCD" alt="" class="profile-photo photo-main">
            <div class="info-user" style=" display: flex;
    width: 100%;
    top: 0;
    left: 0;
    margin-left: 15%;
    margin-top: 25px;
    margin-bottom: 20px;
    flex-direction: column;
    align-items: flex-start;">
                <p class="name" style="font-size: 48px;
    font-weight: bold;
    font-family: arial;">Snaptec Hue</p>
                <p class="quantity-friends" style="    font-size: 23px;
    font-family: arial;
    font-weight: bold;
    color: #65676B;">2 bạn chung</p>
                <span style="display: flex;">
                    <span><img style="width: 2.7rem;
    aspect-ratio: 1/1;
    border-radius: 50%;
    overflow: hidden;" src="https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg" alt="" class="profile-photo"></span>
                    <span><img style="width: 2.7rem;
    aspect-ratio: 1/1;
    border-radius: 50%;
    overflow: hidden;" src="https://www.planetware.com/wpimages/2020/02/france-in-pictures-beautiful-places-to-photograph-eiffel-tower.jpg" alt="" class="profile-photo"></span>
                </span>
                <div id="" class="add-friend js-addfriend" style="display: flex;
    width: 100%;
    justify-content: center;
    align-items: center;
    margin-left: -45px;">
    <button id="" class="add-friend-btn js-addfriend-btn" style="background-color: #E4E6EB;
                border: 0;
    color: #000000;
    padding: 14px 37px;
    font-size: 21px;
    font-weight: 600;
    border-radius: 8px;
    margin-right:10px;">Bạn bè</button>
                <button id="" class="add-friend-btn js-addfriend-btn" style="background-color: #1B74E4;
                border: 0;
    color: #fff;
    padding: 14px 37px;
    font-size: 21px;
    font-weight: 600;
    border-radius: 8px;">Nhắn tin</button>
            </div>
            </div>
            
        </div>
    </div>

</div>