<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="https://www.thebodyshop.com.sa/east/pub/media/absolute_advancedslider/image/cache/1920x/2023-Q1-RAMADAN-GET-READY-GIFT-LFS-CT1-200pc-DT.jpg" alt="First slide">
      <div class="carousel-caption d-none d-md-block" style="left: 50%;
    position: absolute;
    transform: translate(-50%, -50%);
    top: 50%;text-align: center;width:70%; margin-bottom:15px;">
        <strong style="font-size:65px;line-height: 70px;color:#F8F3E8;margin-bottom:30px;
    font-family: arial;
    text-transform: uppercase;">LIFT THEIR SPIRITS</strong>
        <p style="font-family: 'WorkSansRegular';color:#F8F3E8;
    font-size: 28px;
    line-height: 24px;
    font-weight: normal;
    padding-bottom: 0;margin-bottom:40px;font-family:arial;">Celebrate as one with NEW, limited edition, Eid gifts that<br>
          bring joy to more than one.
        </p>
        <div class="button-caption">
          <button style="padding: 10px 45px;
    text-transform: capitalize;border: none;
    background: #004236;
    color: #F8F3E8;font-size:16px;">Shop Gifts Now</button>
      </div>
      </div>
    </div>
  </div>
</div>
